In [2]:
import pandas as pd

In [3]:
installed_capacity = pd.read_csv("/Users/alexanderkell/Documents/SGI/Projects/11-starter-kits/data/raw/starter-kits/kenya/Table1_KEN.csv")
installed_capacity

,Power Generation Technology,Year,Value,Parameter
0,Biomass Power Plant,2015,90.00,Estimated Installed Capacity (MW)
1,Geothermal Power Plant,2015,419.00,Estimated Installed Capacity (MW)
2,Light Fuel Oil Power Plant,2015,287.50,Estimated Installed Capacity (MW)
3,Oil Fired Gas Turbine (SCGT),2015,447.00,Estimated Installed Capacity (MW)
4,Solar PV (Utility),2015,24.00,Estimated Installed Capacity (MW)
5,Large Hydropower Plant (Dam) (>100MW),2015,499.00,Estimated Installed Capacity (MW)
6,Medium Hydropower Plant (10-100MW),2015,320.80,Estimated Installed Capacity (MW)
7,Onshore Wind,2015,336.00,Estimated Installed Capacity (MW)
8,Off-grid Solar PV,2015,37.84,Estimated Installed Capacity (MW)
9,Off-grid Hydropower,2015,6.44,Estimated Installed Capacity (MW)
10,Biomass Power Plant,2016,90.00,Estimated Installed Capacity (MW)
11,Geothermal Power Plant,2016,419.00,Estimated Installed Capacity (MW)
12,Light Fuel Oil Power Plant,2016,287.50,Estimated Installed Capacity (MW)
13,Oil Fired Gas Turbine (SCGT),2016,447.00,Estimated Installed Capacity (MW)
14,Solar PV (Utility),2016,24.00,Estimated Installed Capacity (MW)
15,Large Hydropower Plant (Dam) (>100MW),2016,499.00,Estimated Installed Capacity (MW)
16,Medium Hydropower Plant (10-100MW),2016,320.80,Estimated Installed Capacity (MW)
17,Onshore Wind,2016,336.00,Estimated Installed Capacity (MW)
18,Off-grid Solar PV,2016,37.84,Estimated Installed Capacity (MW)
19,Off-grid Hydropower,2016,6.44,Estimated Installed Capacity (MW)
20,Biomass Power Plant,2017,90.00,Estimated Installed Capacity (MW)
21,Geothermal Power Plant,2017,419.00,Estimated Installed Capacity (MW)
22,Light Fuel Oil Power Plant,2017,287.50,Estimated Installed Capacity (MW)
23,Oil Fired Gas Turbine (SCGT),2017,447.00,Estimated Installed Capacity (MW)
24,Solar PV (Utility),2017,24.00,Estimated Installed Capacity (MW)
25,Large Hydropower Plant (Dam) (>100MW),2017,499.00,Estimated Installed Capacity (MW)
26,Medium Hydropower Plant (10-100MW),2017,320.80,Estimated Installed Capacity (MW)
27,Onshore Wind,2017,336.00,Estimated Installed Capacity (MW)
28,Off-grid Solar PV,2017,37.84,Estimated Installed Capacity (MW)
29,Off-grid Hydropower,2017,6.44,Estimated Installed Capacity (MW)
30,Biomass Power Plant,2018,90.00,Estimated Installed Capacity (MW)
31,Geothermal Power Plant,2018,419.00,Estimated Installed Capacity (MW)
32,Light Fuel Oil Power Plant,2018,287.50,Estimated Installed Capacity (MW)
33,Oil Fired Gas Turbine (SCGT),2018,447.00,Estimated Installed Capacity (MW)
34,Solar PV (Utility),2018,24.00,Estimated Installed Capacity (MW)
35,Large Hydropower Plant (Dam) (>100MW),2018,499.00,Estimated Installed Capacity (MW)
36,Medium Hydropower Plant (10-100MW),2018,248.80,Estimated Installed Capacity (MW)
37,Onshore Wind,2018,310.00,Estimated Installed Capacity (MW)
38,Off-grid Solar PV,2018,37.84,Estimated Installed Capacity (MW)
39,Off-grid Hydropower,2018,6.44,Estimated Installed Capacity (MW)

In [4]:
installed_capacity = installed_capacity.rename(columns={"Power Generation Technology": "Technology"})
installed_capacity.head()

,Technology,Year,Value,Parameter
0,Biomass Power Plant,2015,90.0,Estimated Installed Capacity (MW)
1,Geothermal Power Plant,2015,419.0,Estimated Installed Capacity (MW)
2,Light Fuel Oil Power Plant,2015,287.5,Estimated Installed Capacity (MW)
3,Oil Fired Gas Turbine (SCGT),2015,447.0,Estimated Installed Capacity (MW)
4,Solar PV (Utility),2015,24.0,Estimated Installed Capacity (MW)

In [5]:
latest_installed_capacity = installed_capacity[installed_capacity.Year == installed_capacity['Year'].max()]
latest_installed_capacity

,Technology,Year,Value,Parameter
30,Biomass Power Plant,2018,90.00,Estimated Installed Capacity (MW)
31,Geothermal Power Plant,2018,419.00,Estimated Installed Capacity (MW)
32,Light Fuel Oil Power Plant,2018,287.50,Estimated Installed Capacity (MW)
33,Oil Fired Gas Turbine (SCGT),2018,447.00,Estimated Installed Capacity (MW)
34,Solar PV (Utility),2018,24.00,Estimated Installed Capacity (MW)
35,Large Hydropower Plant (Dam) (>100MW),2018,499.00,Estimated Installed Capacity (MW)
36,Medium Hydropower Plant (10-100MW),2018,248.80,Estimated Installed Capacity (MW)
37,Onshore Wind,2018,310.00,Estimated Installed Capacity (MW)
38,Off-grid Solar PV,2018,37.84,Estimated Installed Capacity (MW)
39,Off-grid Hydropower,2018,6.44,Estimated Installed Capacity (MW)

In [6]:
technoeconomics = pd.read_csv("/Users/alexanderkell/Documents/SGI/Projects/11-starter-kits/data/raw/starter-kits/kenya/Table2_KEN.csv")
technoeconomics

,Technology,Parameter,Value
0,Biomass Power Plant,Capital Cost ($/kW in 2020),2500.00
1,Coal Power Plant,Capital Cost ($/kW in 2020),2500.00
2,Geothermal Power Plant,Capital Cost ($/kW in 2020),4000.00
3,Light Fuel Oil Power Plant,Capital Cost ($/kW in 2020),1200.00
4,Oil Fired Gas Turbine (SCGT),Capital Cost ($/kW in 2020),1450.00
...,...,...,...
85,Onshore Wind,Average Capacity Factor,0.21
86,Offshore Wind,Average Capacity Factor,0.45
87,Nuclear Power Plant,Average Capacity Factor,0.85
88,Light Fuel Oil Standalone Generator (1kW),Average Capacity Factor,0.30
89,Solar PV (Distributed with Storage),Average Capacity Factor,0.32

In [7]:
installed_capacity_cf = latest_installed_capacity.merge(technoeconomics[technoeconomics.Parameter == "Average Capacity Factor"], on="Technology")
installed_capacity_cf = installed_capacity_cf.rename(columns={"Value_y": "average_capacity_factor", "Value_x": "estimated_installed_capacity_MW"})
installed_capacity_cf = installed_capacity_cf.drop(columns=["Parameter_y", "Parameter_x"])
installed_capacity_cf

,Technology,Year,estimated_installed_capacity_MW,average_capacity_factor
0,Biomass Power Plant,2018,90.0,0.50
1,Geothermal Power Plant,2018,419.0,0.79
2,Light Fuel Oil Power Plant,2018,287.5,0.80
3,Oil Fired Gas Turbine (SCGT),2018,447.0,0.80
4,Solar PV (Utility),2018,24.0,0.32
5,Large Hydropower Plant (Dam) (>100MW),2018,499.0,0.48
6,Medium Hydropower Plant (10-100MW),2018,248.8,0.48
7,Onshore Wind,2018,310.0,0.21

In [8]:
installed_capacity_cf['estimated_installed_capacity_PJ_y'] = installed_capacity_cf.estimated_installed_capacity_MW * 365 * installed_capacity_cf.average_capacity_factor
installed_capacity_cf

,Technology,Year,estimated_installed_capacity_MW,average_capacity_factor,estimated_installed_capacity_PJ_y
0,Biomass Power Plant,2018,90.0,0.50,16425.00
1,Geothermal Power Plant,2018,419.0,0.79,120818.65
2,Light Fuel Oil Power Plant,2018,287.5,0.80,83950.00
3,Oil Fired Gas Turbine (SCGT),2018,447.0,0.80,130524.00
4,Solar PV (Utility),2018,24.0,0.32,2803.20
5,Large Hydropower Plant (Dam) (>100MW),2018,499.0,0.48,87424.80
6,Medium Hydropower Plant (10-100MW),2018,248.8,0.48,43589.76
7,Onshore Wind,2018,310.0,0.21,23761.50

In [9]:
installed_capacity_pj_y = installed_capacity_cf.drop(columns=["estimated_installed_capacity_MW","average_capacity_factor"])
installed_capacity_pj_y

,Technology,Year,estimated_installed_capacity_PJ_y
0,Biomass Power Plant,2018,16425.00
1,Geothermal Power Plant,2018,120818.65
2,Light Fuel Oil Power Plant,2018,83950.00
3,Oil Fired Gas Turbine (SCGT),2018,130524.00
4,Solar PV (Utility),2018,2803.20
5,Large Hydropower Plant (Dam) (>100MW),2018,87424.80
6,Medium Hydropower Plant (10-100MW),2018,43589.76
7,Onshore Wind,2018,23761.50

In [10]:
installed_capacity_pj_y_wide = installed_capacity_pj_y.pivot(index='Technology', columns='Year', values='estimated_installed_capacity_PJ_y').reset_index()
installed_capacity_pj_y_wide

Year                             Technology       2018
0                       Biomass Power Plant   16425.00
1                    Geothermal Power Plant  120818.65
2     Large Hydropower Plant (Dam) (>100MW)   87424.80
3                Light Fuel Oil Power Plant   83950.00
4        Medium Hydropower Plant (10-100MW)   43589.76
5              Oil Fired Gas Turbine (SCGT)  130524.00
6                              Onshore Wind   23761.50
7                        Solar PV (Utility)    2803.20

In [11]:
unknown_cols = list(range(2020, 2052, 2))
for col in unknown_cols:
    installed_capacity_pj_y_wide[col] = 0
installed_capacity_pj_y_wide

Year,Technology,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050
0,Biomass Power Plant,16425.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Geothermal Power Plant,120818.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Large Hydropower Plant (Dam) (>100MW),87424.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Light Fuel Oil Power Plant,83950.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Medium Hydropower Plant (10-100MW),43589.76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Oil Fired Gas Turbine (SCGT),130524.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,Onshore Wind,23761.50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,Solar PV (Utility),2803.20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [12]:
installed_capacity_pj_y_wide.insert(1, "RegionName", "R1" )
installed_capacity_pj_y_wide.insert(2, "Unit", "PJ/y" )
installed_capacity_pj_y_wide

Year,Technology,RegionName,Unit,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050
0,Biomass Power Plant,R1,PJ/y,16425.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Geothermal Power Plant,R1,PJ/y,120818.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Large Hydropower Plant (Dam) (>100MW),R1,PJ/y,87424.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Light Fuel Oil Power Plant,R1,PJ/y,83950.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Medium Hydropower Plant (10-100MW),R1,PJ/y,43589.76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Oil Fired Gas Turbine (SCGT),R1,PJ/y,130524.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,Onshore Wind,R1,PJ/y,23761.50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,Solar PV (Utility),R1,PJ/y,2803.20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [14]:
muse_installed_capacity = installed_capacity_pj_y_wide.rename(columns={"Technology":"ProcessName"}).set_index("ProcessName")
muse_installed_capacity

Year,RegionName,Unit,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050
ProcessName,,,,,,,,,,,,,,,,,,,
Biomass Power Plant,R1,PJ/y,16425.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Geothermal Power Plant,R1,PJ/y,120818.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Large Hydropower Plant (Dam) (>100MW),R1,PJ/y,87424.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Light Fuel Oil Power Plant,R1,PJ/y,83950.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Medium Hydropower Plant (10-100MW),R1,PJ/y,43589.76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Oil Fired Gas Turbine (SCGT),R1,PJ/y,130524.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Onshore Wind,R1,PJ/y,23761.50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Solar PV (Utility),R1,PJ/y,2803.20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Oil installed capacity

This is zero for all as there is no data available

In [16]:
oil_techno = pd.read_csv("/Users/alexanderkell/Documents/SGI/Projects/11-starter-kits/data/raw/starter-kits/Kenya/Table5_KEN.csv")
oil_techno

,Technology,Parameter,Value
0,Crude Oil Refinery Option 1,Capital Cost ($/kW in 2020),24.1
1,Crude Oil Refinery Option 2,Capital Cost ($/kW in 2020),24.1
2,Crude Oil Refinery Option 1,Variable Cost ($/GJ in 2020),0.71775
3,Crude Oil Refinery Option 2,Variable Cost ($/GJ in 2020),0.71775
4,Crude Oil Refinery Option 1,Operational Life (years),35
5,Crude Oil Refinery Option 2,Operational Life (years),35
6,Crude Oil Refinery Option 1,Output Ratio,0.9 LFO : 0.1 HFO
7,Crude Oil Refinery Option 2,Output Ratio,0.8 LFO : 0.2 HFO

In [19]:
oil_techs = list(pd.unique(oil_techno.Technology))
oil_techs

['Crude Oil Refinery Option 1', 'Crude Oil Refinery Option 2']

In [28]:
existing_capacity_dict = {}
for tech in oil_techs:
    existing_capacity_dict[tech] = [tech, "Kenya", "PJ/y"] + [0]*17
    
existing_capacity_dict

{'Crude Oil Refinery Option 1': ['Crude Oil Refinery Option 1',
  'Kenya',
  'PJ/y',
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Crude Oil Refinery Option 2': ['Crude Oil Refinery Option 2',
  'Kenya',
  'PJ/y',
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [32]:
oil_existing_capacity = pd.DataFrame.from_dict(existing_capacity_dict, orient="index", columns = ['ProcessName', "RegionName", "Unit"] + list(range(2018, 2052, 2)))
oil_existing_capacity.reset_index(drop=True)

# list(range(2018, 2052, 2))

,ProcessName,RegionName,Unit,2018,2020,2022,2024,2026,2028,2030,2032,2034,2036,2038,2040,2042,2044,2046,2048,2050
0,Crude Oil Refinery Option 1,Kenya,PJ/y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Crude Oil Refinery Option 2,Kenya,PJ/y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0