In [93]:
import pandas as pd

In [94]:
costs = pd.read_csv("/Users/alexanderkell/Documents/SGI/Projects/11-starter-kits/data/raw/starter-kits/Kenya/Table6_KEN.csv")
costs

                 Commodity  Year  Value             Parameter
0        Crude Oil Imports  2015  13.14  Variable Cost ($/GJ)
1     Crude Oil Extraction  2015  11.95  Variable Cost ($/GJ)
2          Biomass Imports  2015   1.76  Variable Cost ($/GJ)
3       Biomass Extraction  2015   1.60  Variable Cost ($/GJ)
4             Coal Imports  2015   4.90  Variable Cost ($/GJ)
..                     ...   ...    ...                   ...
65         Coal Extraction  2060   3.80  Variable Cost ($/GJ)
66  Light Fuel Oil Imports  2060  26.79  Variable Cost ($/GJ)
67  Heavy Fuel Oil Imports  2060  16.11  Variable Cost ($/GJ)
68     Natural Gas Imports  2060  11.00  Variable Cost ($/GJ)
69  Natural Gas Extraction  2060   9.90  Variable Cost ($/GJ)

[70 rows x 4 columns]

In [95]:
import_costs = costs[~costs['Commodity'].str.contains("Extraction")]
import_costs

                 Commodity  Year  Value             Parameter
0        Crude Oil Imports  2015  13.14  Variable Cost ($/GJ)
2          Biomass Imports  2015   1.76  Variable Cost ($/GJ)
4             Coal Imports  2015   4.90  Variable Cost ($/GJ)
6   Light Fuel Oil Imports  2015  15.89  Variable Cost ($/GJ)
7   Heavy Fuel Oil Imports  2015   9.56  Variable Cost ($/GJ)
8      Natural Gas Imports  2015   8.60  Variable Cost ($/GJ)
10       Crude Oil Imports  2020  12.20  Variable Cost ($/GJ)
12         Biomass Imports  2020   1.76  Variable Cost ($/GJ)
14            Coal Imports  2020   5.10  Variable Cost ($/GJ)
16  Light Fuel Oil Imports  2020  14.75  Variable Cost ($/GJ)
17  Heavy Fuel Oil Imports  2020   8.87  Variable Cost ($/GJ)
18     Natural Gas Imports  2020   8.60  Variable Cost ($/GJ)
20       Crude Oil Imports  2025  12.76  Variable Cost ($/GJ)
22         Biomass Imports  2025   1.76  Variable Cost ($/GJ)
24            Coal Imports  2025   5.30  Variable Cost ($/GJ)
26  Light Fuel Oil Imports  2025  15.43  Variable Cost ($/GJ)
27  Heavy Fuel Oil Imports  2025   9.28  Variable Cost ($/GJ)
28     Natural Gas Imports  2025   9.45  Variable Cost ($/GJ)
30       Crude Oil Imports  2030  14.27  Variable Cost ($/GJ)
32         Biomass Imports  2030   1.76  Variable Cost ($/GJ)
34            Coal Imports  2030   5.50  Variable Cost ($/GJ)
36  Light Fuel Oil Imports  2030  17.25  Variable Cost ($/GJ)
37  Heavy Fuel Oil Imports  2030  10.38  Variable Cost ($/GJ)
38     Natural Gas Imports  2030  10.30  Variable Cost ($/GJ)
40       Crude Oil Imports  2040  16.90  Variable Cost ($/GJ)
42         Biomass Imports  2040   1.76  Variable Cost ($/GJ)
44            Coal Imports  2040   5.90  Variable Cost ($/GJ)
46  Light Fuel Oil Imports  2040  20.43  Variable Cost ($/GJ)
47  Heavy Fuel Oil Imports  2040  12.29  Variable Cost ($/GJ)
48     Natural Gas Imports  2040  11.00  Variable Cost ($/GJ)
50       Crude Oil Imports  2050  19.53  Variable Cost ($/GJ)
52         Biomass Imports  2050   1.76  Variable Cost ($/GJ)
54            Coal Imports  2050   5.90  Variable Cost ($/GJ)
56  Light Fuel Oil Imports  2050  23.61  Variable Cost ($/GJ)
57  Heavy Fuel Oil Imports  2050  14.20  Variable Cost ($/GJ)
58     Natural Gas Imports  2050  11.00  Variable Cost ($/GJ)
60       Crude Oil Imports  2060  22.15  Variable Cost ($/GJ)
62         Biomass Imports  2060   1.76  Variable Cost ($/GJ)
64            Coal Imports  2060   5.90  Variable Cost ($/GJ)
66  Light Fuel Oil Imports  2060  26.79  Variable Cost ($/GJ)
67  Heavy Fuel Oil Imports  2060  16.11  Variable Cost ($/GJ)
68     Natural Gas Imports  2060  11.00  Variable Cost ($/GJ)

In [96]:
import_costs['Commodity'] = import_costs['Commodity'].str.replace("Imports", "")
import_costs['Commodity'] = import_costs['Commodity'].str.replace("Natural", "")
import_costs['Commodity'] = import_costs['Commodity'].str.lower()
import_costs['Commodity'] = import_costs['Commodity'].str.replace("light fuel oil", "LFO")
import_costs['Commodity'] = import_costs['Commodity'].str.replace("heavy fuel oil", "HFO")
import_costs['Commodity'] = import_costs['Commodity'].str.replace(" ", "")
import_costs['Commodity'] = import_costs['Commodity'].str.replace("crudeoil", "crude_oil")
import_costs

<ipython-input-96-1fdd1c78d38e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.replace("Imports", "")
<ipython-input-96-1fdd1c78d38e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.replace("Natural", "")
<ipython-input-96-1fdd1c78d38e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.lower()
<ipython-input-96-1fdd1c78d38e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.replace("light fuel oil", "LFO")
<ipython-input-96-1fdd1c78d38e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.replace("heavy fuel oil", "HFO")
<ipython-input-96-1fdd1c78d38e>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.replace(" ", "")
<ipython-input-96-1fdd1c78d38e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import_costs['Commodity'] = import_costs['Commodity'].str.replace("crudeoil", "crude_oil")

    Commodity  Year  Value             Parameter
0   crude_oil  2015  13.14  Variable Cost ($/GJ)
2     biomass  2015   1.76  Variable Cost ($/GJ)
4        coal  2015   4.90  Variable Cost ($/GJ)
6         LFO  2015  15.89  Variable Cost ($/GJ)
7         HFO  2015   9.56  Variable Cost ($/GJ)
8         gas  2015   8.60  Variable Cost ($/GJ)
10  crude_oil  2020  12.20  Variable Cost ($/GJ)
12    biomass  2020   1.76  Variable Cost ($/GJ)
14       coal  2020   5.10  Variable Cost ($/GJ)
16        LFO  2020  14.75  Variable Cost ($/GJ)
17        HFO  2020   8.87  Variable Cost ($/GJ)
18        gas  2020   8.60  Variable Cost ($/GJ)
20  crude_oil  2025  12.76  Variable Cost ($/GJ)
22    biomass  2025   1.76  Variable Cost ($/GJ)
24       coal  2025   5.30  Variable Cost ($/GJ)
26        LFO  2025  15.43  Variable Cost ($/GJ)
27        HFO  2025   9.28  Variable Cost ($/GJ)
28        gas  2025   9.45  Variable Cost ($/GJ)
30  crude_oil  2030  14.27  Variable Cost ($/GJ)
32    biomass  2030   1.76  Variable Cost ($/GJ)
34       coal  2030   5.50  Variable Cost ($/GJ)
36        LFO  2030  17.25  Variable Cost ($/GJ)
37        HFO  2030  10.38  Variable Cost ($/GJ)
38        gas  2030  10.30  Variable Cost ($/GJ)
40  crude_oil  2040  16.90  Variable Cost ($/GJ)
42    biomass  2040   1.76  Variable Cost ($/GJ)
44       coal  2040   5.90  Variable Cost ($/GJ)
46        LFO  2040  20.43  Variable Cost ($/GJ)
47        HFO  2040  12.29  Variable Cost ($/GJ)
48        gas  2040  11.00  Variable Cost ($/GJ)
50  crude_oil  2050  19.53  Variable Cost ($/GJ)
52    biomass  2050   1.76  Variable Cost ($/GJ)
54       coal  2050   5.90  Variable Cost ($/GJ)
56        LFO  2050  23.61  Variable Cost ($/GJ)
57        HFO  2050  14.20  Variable Cost ($/GJ)
58        gas  2050  11.00  Variable Cost ($/GJ)
60  crude_oil  2060  22.15  Variable Cost ($/GJ)
62    biomass  2060   1.76  Variable Cost ($/GJ)
64       coal  2060   5.90  Variable Cost ($/GJ)
66        LFO  2060  26.79  Variable Cost ($/GJ)
67        HFO  2060  16.11  Variable Cost ($/GJ)
68        gas  2060  11.00  Variable Cost ($/GJ)

In [97]:
fuels = list(pd.unique(import_costs.Commodity))
fuels

['crude_oil', 'biomass', 'coal', 'LFO', 'HFO', 'gas']

In [98]:
projections = import_costs.pivot_table(index="Year", columns="Commodity", values="Value")
projections

Commodity    HFO    LFO  biomass  coal  crude_oil    gas
Year
2015        9.56  15.89     1.76   4.9      13.14   8.60
2020        8.87  14.75     1.76   5.1      12.20   8.60
2025        9.28  15.43     1.76   5.3      12.76   9.45
2030       10.38  17.25     1.76   5.5      14.27  10.30
2040       12.29  20.43     1.76   5.9      16.90  11.00
2050       14.20  23.61     1.76   5.9      19.53  11.00
2060       16.11  26.79     1.76   5.9      22.15  11.00

In [99]:
projections['RegionName'] = "Kenya"
projections['Attribute'] = "CommodityPrice"
projections

Commodity,HFO,LFO,biomass,coal,crude_oil,gas,RegionName,Attribute
Year,,,,,,,,
2015,9.56,15.89,1.76,4.9,13.14,8.60,Kenya,CommodityPrice
2020,8.87,14.75,1.76,5.1,12.20,8.60,Kenya,CommodityPrice
2025,9.28,15.43,1.76,5.3,12.76,9.45,Kenya,CommodityPrice
2030,10.38,17.25,1.76,5.5,14.27,10.30,Kenya,CommodityPrice
2040,12.29,20.43,1.76,5.9,16.90,11.00,Kenya,CommodityPrice
2050,14.20,23.61,1.76,5.9,19.53,11.00,Kenya,CommodityPrice
2060,16.11,26.79,1.76,5.9,22.15,11.00,Kenya,CommodityPrice

In [100]:
projections = projections.reset_index()
projections = projections.rename(columns={"Year": "Time"})
projections

Commodity,Time,HFO,LFO,biomass,coal,crude_oil,gas,RegionName,Attribute
0,2015,9.56,15.89,1.76,4.9,13.14,8.60,Kenya,CommodityPrice
1,2020,8.87,14.75,1.76,5.1,12.20,8.60,Kenya,CommodityPrice
2,2025,9.28,15.43,1.76,5.3,12.76,9.45,Kenya,CommodityPrice
3,2030,10.38,17.25,1.76,5.5,14.27,10.30,Kenya,CommodityPrice
4,2040,12.29,20.43,1.76,5.9,16.90,11.00,Kenya,CommodityPrice
5,2050,14.20,23.61,1.76,5.9,19.53,11.00,Kenya,CommodityPrice
6,2060,16.11,26.79,1.76,5.9,22.15,11.00,Kenya,CommodityPrice

In [101]:
muse_projections = pd.read_csv("/Users/alexanderkell/Documents/SGI/Projects/11-starter-kits/data/external/muse_data/default/input/Projections.csv")
muse_projections.head()

,RegionName,Attribute,Time,electricity,gas,heat,CO2f,wind
0,Unit,-,Year,MUS$2010/PJ,MUS$2010/PJ,MUS$2010/PJ,MUS$2010/kt,MUS$2010/kt
1,R1,CommodityPrice,2010,14.81481472,6.6759,100,0,0
2,R1,CommodityPrice,2015,17.89814806,6.914325,100,0.052913851,0
3,R1,CommodityPrice,2020,19.5,7.15275,100,0.08314119,0
4,R1,CommodityPrice,2025,21.93518528,8.10645,100,0.120069795,0

In [102]:
projections

Commodity,Time,HFO,LFO,biomass,coal,crude_oil,gas,RegionName,Attribute
0,2015,9.56,15.89,1.76,4.9,13.14,8.60,Kenya,CommodityPrice
1,2020,8.87,14.75,1.76,5.1,12.20,8.60,Kenya,CommodityPrice
2,2025,9.28,15.43,1.76,5.3,12.76,9.45,Kenya,CommodityPrice
3,2030,10.38,17.25,1.76,5.5,14.27,10.30,Kenya,CommodityPrice
4,2040,12.29,20.43,1.76,5.9,16.90,11.00,Kenya,CommodityPrice
5,2050,14.20,23.61,1.76,5.9,19.53,11.00,Kenya,CommodityPrice
6,2060,16.11,26.79,1.76,5.9,22.15,11.00,Kenya,CommodityPrice

In [103]:
col_order = ["RegionName", "Attribute", "Time"] + fuels
projections = projections[col_order]
projections

Commodity,RegionName,Attribute,Time,crude_oil,biomass,coal,LFO,HFO,gas
0,Kenya,CommodityPrice,2015,13.14,1.76,4.9,15.89,9.56,8.60
1,Kenya,CommodityPrice,2020,12.20,1.76,5.1,14.75,8.87,8.60
2,Kenya,CommodityPrice,2025,12.76,1.76,5.3,15.43,9.28,9.45
3,Kenya,CommodityPrice,2030,14.27,1.76,5.5,17.25,10.38,10.30
4,Kenya,CommodityPrice,2040,16.90,1.76,5.9,20.43,12.29,11.00
5,Kenya,CommodityPrice,2050,19.53,1.76,5.9,23.61,14.20,11.00
6,Kenya,CommodityPrice,2060,22.15,1.76,5.9,26.79,16.11,11.00

In [104]:
units = {
    "ProcessName": ["Unit"],
    "RegionName": ["-"],
    "Time": ["Year"],
    "Level": ["-"],
    "CO2f": ["kt/PJ"],
    "biomass": ["PJ/PJ"],
    "coal": ["PJ/PJ"],
    "gas": ["PJ/PJ"],
    "geothermal": ["PJ/PJ"],
    "hydro": ["PJ/PJ"],
    "HFO": ["PJ/PJ"],
    "LFO": ["PJ/PJ"],
    "crude_oil": ["PJ/PJ"],
    "solar": ["PJ/PJ"],
    "uranium": ["PJ/PJ"],
    "wind": ["PJ/PJ"],
    "electricity": ["PJ/PJ"],
    "heat": ["PJ/PJ"],
}

commodities = units.copy()
for item in ["ProcessName", "RegionName", "Time", "Level", "crude_oil", "biomass", "coal", "LFO", "HFO", "gas"]:
    commodities.pop(item)

for key, _ in commodities.items():
    projections[key] = 0

projections

<ipython-input-104-da8d026ac1c7>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  projections[key] = 0

Commodity,RegionName,Attribute,Time,crude_oil,biomass,coal,LFO,HFO,gas,CO2f,geothermal,hydro,solar,uranium,wind,electricity,heat
0,Kenya,CommodityPrice,2015,13.14,1.76,4.9,15.89,9.56,8.60,0,0,0,0,0,0,0,0
1,Kenya,CommodityPrice,2020,12.20,1.76,5.1,14.75,8.87,8.60,0,0,0,0,0,0,0,0
2,Kenya,CommodityPrice,2025,12.76,1.76,5.3,15.43,9.28,9.45,0,0,0,0,0,0,0,0
3,Kenya,CommodityPrice,2030,14.27,1.76,5.5,17.25,10.38,10.30,0,0,0,0,0,0,0,0
4,Kenya,CommodityPrice,2040,16.90,1.76,5.9,20.43,12.29,11.00,0,0,0,0,0,0,0,0
5,Kenya,CommodityPrice,2050,19.53,1.76,5.9,23.61,14.20,11.00,0,0,0,0,0,0,0,0
6,Kenya,CommodityPrice,2060,22.15,1.76,5.9,26.79,16.11,11.00,0,0,0,0,0,0,0,0

In [105]:
units = {"RegionName": ["Unit"], "Attribute": ["-"], "Time": ["Year"]}
for commodity in fuels + list(commodities.keys()):
    units[commodity] = ["$/GJ"]
    
units

{'RegionName': ['Unit'],
 'Attribute': ['-'],
 'Time': ['Year'],
 'crude_oil': ['$/GJ'],
 'biomass': ['$/GJ'],
 'coal': ['$/GJ'],
 'LFO': ['$/GJ'],
 'HFO': ['$/GJ'],
 'gas': ['$/GJ'],
 'CO2f': ['$/GJ'],
 'geothermal': ['$/GJ'],
 'hydro': ['$/GJ'],
 'solar': ['$/GJ'],
 'uranium': ['$/GJ'],
 'wind': ['$/GJ'],
 'electricity': ['$/GJ'],
 'heat': ['$/GJ']}

In [106]:
units_row = pd.DataFrame.from_dict(units, orient="columns")
projections_out = units_row.append(projections)
projections_out

Commodity,RegionName,Attribute,Time,crude_oil,biomass,coal,LFO,HFO,gas,CO2f,geothermal,hydro,solar,uranium,wind,electricity,heat
0,Unit,-,Year,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ,$/GJ
0,Kenya,CommodityPrice,2015,13.14,1.76,4.9,15.89,9.56,8.6,0,0,0,0,0,0,0,0
1,Kenya,CommodityPrice,2020,12.2,1.76,5.1,14.75,8.87,8.6,0,0,0,0,0,0,0,0
2,Kenya,CommodityPrice,2025,12.76,1.76,5.3,15.43,9.28,9.45,0,0,0,0,0,0,0,0
3,Kenya,CommodityPrice,2030,14.27,1.76,5.5,17.25,10.38,10.3,0,0,0,0,0,0,0,0
4,Kenya,CommodityPrice,2040,16.9,1.76,5.9,20.43,12.29,11,0,0,0,0,0,0,0,0
5,Kenya,CommodityPrice,2050,19.53,1.76,5.9,23.61,14.2,11,0,0,0,0,0,0,0,0
6,Kenya,CommodityPrice,2060,22.15,1.76,5.9,26.79,16.11,11,0,0,0,0,0,0,0,0